matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - cd $TRAVIS_BUILD_DIR/server/glsp-ecore && mvn clean verify
    - language: node_js
      script:
        - cd $TRAVIS_BUILD_DIR/client/theia-ecore && yarn install
